### ISSUE TITLE
[BUG] Automatic transaction generator not working anymore

### ISSUE THREAD

**Issue by dupste** [jerome-benoit/charging-stations-simulator#201]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

When setting AutomaticTransactionGenerator.enable to true, with valid badge list, no transaction is triggered after full onboarding of the charging station.
Environment: https://testcpoperf-p97l01k4-ev-approuter-emobility-perf-cpo.cfapps.eu10.hana.ondemand.com/logs

### charging-stations-simulator version

1.1.56

### Node.js Version

14.19

### System

 System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 2.55 GB / 15.84 GB

### Expected result

It is expected that the simulated charging station will send an Authorize and StartTransaction after connecting to the system.

### Actual result

Simulated charging station connects but doesn't trigger any further action after onboarding. In the simulator logs, following entries can be observed:
info: 3/24/2022, 10:54:43 PM CS-SCHNEIDER-TEST3-00001 | ATG on connector #2: started on connector and will run for 03:00:00
info: 3/24/2022, 10:54:43 PM CS-SCHNEIDER-TEST3-00001 | ATG on connector #2: entered in transaction loop while the charging station is unavailable    
warn: 3/24/2022, 10:54:43 PM CS-SCHNEIDER-TEST3-00001 | ATG on connector #2: trying to stop a not started transaction
info: 3/24/2022, 10:54:43 PM CS-SCHNEIDER-TEST3-00001 | ATG on connector #2: stopped on connector and lasted for 00:00:00.001

### Attachments

[config.zip](https://github.com/jerome-benoit/charging-stations-simulator/files/8345942/config.zip)

**Comment by jerome-benoit** [comment]
`info: 3/24/2022, 10:54:43 PM CS-SCHNEIDER-TEST3-00001 | ATG on connector https://github.com/jerome-benoit/charging-stations-simulator/pull/2: entered in transaction loop while the charging station is unavailable`

The charging station has been set as not available by the central server at some point and have not put it back as available?

**Comment by dupste** [comment]
That's a good point, I have observed on real charging stations that they
appear as unavailable after being restarted with the authorization URL...
So there might be an issue to fix on E-Mobility side.


Le jeu. 24 mars 2022 à 23:02, Jérôme Benoit ***@***.***> a
écrit :

**Comment by jerome-benoit** [comment]
@dupste: I think that issue can be closed, right?

**Comment by dupste** [comment]
Issue to be fixed on OCPP server side, closing this ticket.
