### ISSUE TITLE
[BUG] Automatic charging station onboarding

### ISSUE THREAD

**Issue by dupste** [jerome-benoit/charging-stations-simulator#215]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

When using latest version of the simulator in master, automatic onboarding of charging stations is not working anymore.
With 1.1.58 it works fine, but likely commit 01efc60a72a948518a312252b415e74cf43208a7 has introduced a regression.

Attached the config used, with schneider station and automatic transaction generator enabled.

### charging-stations-simulator version

Version 1.1.58 latest commit on master (db5a5d93848e4ba9520df946e04f74c78cb1dd12)

### Node.js Version

v16.14.2

### System

System:
    OS: Linux 4.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 1.31 GB / 15.84 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash

### Expected result

Charging stations are onboarded in Accepted status.

### Actual result

Charging stations remain in pending status.

### Attachments

[configfiles.zip](https://github.com/jerome-benoit/charging-stations-simulator/files/8556815/configfiles.zip)

**Comment by jerome-benoit** [comment]
It's not related to the simulator, it's server side bug regarding template matching: 

`No template matching the charging station has been found but one matched previously. Keeping the previous template configuration`

**Comment by jerome-benoit** [comment]
The issue is that in master, the notification is now truncated and miss some information in the CS templates. So the server fail to find a matching autoconfiguration template.
