### ISSUE TITLE
[QUERY] "Unexpected token ?" when starting the simulator

### ISSUE THREAD

**Issue by Pulse-akhil** [jerome-benoit/charging-stations-simulator#55]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

**Steps to reproduce** 
1. enter OCPP url into config.json under /src/assets.
2. rename authorization-tags-template.json to authorization-tags.json. 
3. Leave station-template.json files inside "station-templates" folder under src/assets 

**Command executed** - "npm start" 

**Output received**
 
created dist in 14.4s

> charging-stations-simulator@1.1.7 start /root/charging-stations-simulator
> cross-env NODE_ENV=production node -r source-map-support/register dist/start.js

/root/charging-stations-simulator/dist/charging-station/Bootstrap.js:1
"use strict";var e=require("../types/Worker.js"),t=require("../utils/Configuration.js"),r=require("../performance/storage/StorageFactory.js"),o=require("../utils/Utils.js"),a=require("../worker/WorkerFactory.js"),n=require("chalk"),i=require("worker_threads"),s=require("path"),l=require("../package.json.js");function g(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var c=g(n),m=g(s);class u{constructor(){this.version=l.version,this.started=!1,this.workerScript=m.default.join(m.default.resolve(__dirname,"../"),"charging-station","ChargingStationWorker.js"),this.initWorkerImplementation(),u.storage=r.StorageFactory.getStorage(t.getPerformanceStorage().type,t.getPerformanceStorage().URI,this.logPrefix()),t.setConfigurationChangeCallback((async()=>u.getInstance().restart()))}static getInstance(){return u.instance||(u.instance=new u),u.instance}async start(){if(i.isMainThread&&!this.started)try{if(u.numberOfChargingStations=0,aw

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/charging-stations-simulator/dist/start.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! charging-stations-simulator@1.1.7 start: `cross-env NODE_ENV=production node -r source-map-support/register dist/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the charging-stations-simulator@1.1.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### charging-stations-simulator version

latest

### Node.js Version

10.19

### System

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (1) x64 DO-Premium-AMD
    Memory: 564.75 MB / 981.30 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash

### Expected result

Was expecting the app to run and connect to the OCPP server

### Actual result

got this error 

created dist in 14.4s

> charging-stations-simulator@1.1.7 start /root/charging-stations-simulator
> cross-env NODE_ENV=production node -r source-map-support/register dist/start.js

/root/charging-stations-simulator/dist/charging-station/Bootstrap.js:1
"use strict";var e=require("../types/Worker.js"),t=require("../utils/Configuration.js"),r=require("../performance/storage/StorageFactory.js"),o=require("../utils/Utils.js"),a=require("../worker/WorkerFactory.js"),n=require("chalk"),i=require("worker_threads"),s=require("path"),l=require("../package.json.js");function g(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var c=g(n),m=g(s);class u{constructor(){this.version=l.version,this.started=!1,this.workerScript=m.default.join(m.default.resolve(__dirname,"../"),"charging-station","ChargingStationWorker.js"),this.initWorkerImplementation(),u.storage=r.StorageFactory.getStorage(t.getPerformanceStorage().type,t.getPerformanceStorage().URI,this.logPrefix()),t.setConfigurationChangeCallback((async()=>u.getInstance().restart()))}static getInstance(){return u.instance||(u.instance=new u),u.instance}async start(){if(i.isMainThread&&!this.started)try{if(u.numberOfChargingStations=0,aw

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/charging-stations-simulator/dist/start.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! charging-stations-simulator@1.1.7 start: `cross-env NODE_ENV=production node -r source-map-support/register dist/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the charging-stations-simulator@1.1.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Attachments

None

**Comment by jerome-benoit** [comment]
Hello, could you please attach the charging station template file and the simulator configuration file used? It really looks like a syntax error in one of it.

**Comment by jerome-benoit** [comment]
No answer from the reporter, so let's assume it's not an issue.
